### ISSUE TITLE
Delete squad without loading it

### ISSUE THREAD

**Issue by Isbiten** [geordanr/xwing#129]
This would be a great feature.
As it is now it is quite cumbersome to delete a squad.

**Comment by Kumagoro42** [comment]
Aww, now squads don't load anymore by just clicking anywhere on them, though. I found that very swift to change from one to the other.

**Comment by geordanr** [comment]
Yeah.  I thought I was the only one who did that...  Code-wise (and behavior-wise), it's cleaner to require that the Load button actually gets clicked.  (I had always thought it was sloppy of me to have left it in that state.)

**Comment by Kumagoro42** [comment]
I guess it's cleaner, but it makes life harder on a tablet (which is where I'm using it the most, keeping it at the battlefield's borders).
