### ISSUE TITLE
German Card / Text VT-49 & YT-2400

### ISSUE THREAD

**Issue by Barlmoro** [geordanr/xwing#133]
Here is an overview of the german cards:

http://moseisleyraumhafen.forumieren.com/t1386p15-komplette-kartenubersicht#52351

http://moseisleyraumhafen.forumieren.com/t1386p15-komplette-kartenubersicht#52353

**Comment by strikegun** [comment]
HI, ich helfe geordanr bei der Deutschenübersetzung. Falls du Fehler findest bin ich dir dankbar.

**Comment by strikegun** [comment]
can be closed
