### ISSUE TITLE
Json import does not work

### ISSUE THREAD

**Issue by dmborque314** [geordanr/xwing#134]
I'm having problems when importing this json:

 {"version":"0.1.1","name":"scum2","faction":"scum","pilots":[{"name":"serissu","ship":"m3ainterceptor","upgrades":{"title":["heavyscykinterceptor"],"torpedo":["flechettetorpedoes"]}},{"name":"bobafett","ship":"firespray31","upgrades":{"title":["slavei"],"torpedo":["protontorpedoes"]}},{"name":"kathscarlet","ship":"firespray31"}],"description":"","points":105,"vendor":{"xwsd":{"builder":"X-Wing Squads Designer","builder-link":"https://play.google.com/store/apps/details?id=es.dmb.xws"}}}

Ships and pilots are correctly created but no upgrade is loaded.
Greetings!
David

**Comment by geordanr** [comment]
I think this works now (probably just forgot to close it).  Reopen if it's still an issue.
