### ISSUE TITLE
German Text for YT-2400

### ISSUE THREAD

**Issue by Barlmoro** [geordanr/xwing#135]
Wild Space Fringer(Grenzgänger aus dem Wilden Raum)
Eaden VRill => Wirf 1 zusätzlichen Angriffswürfel, wenn du mit den Primärwaffen auf ein Schiff mit Stressmarker schießt
Leebo => Immer wenn du eine offene Schadenskarte erhälst, ziehst du 1 weitere Schadenskarte, Wähle 1, die abgehandelt wird, und lege die andere ab.
Dash Rendar => Du darfst in der Aktivierungsphase und beim Durchführen von Aktionen Hindernisse ignorieren
Countermeasues(Gegenmaßnahmen) => Zu Beginn der Kampfphase kannst du diese Karte ablegen, um deine Wendigkeit bis zum Ende der Runde um 1 zu erhöhen. Dann darfst du 1 feindliche Zielerfassung von deinem Schiff entfernen.
Experimental Interface (Experimentelles Interface)= Ein Mal pro Runde darfst du nach dem Durchführen einer Aktion 1 ausgerüstete Aufwertungskarte mit dem Stichwort "Aktion:" benutzen(dies zählt als freie Aktion). Dann erhälst du 1 Stressmarker.
Outrider => Solange du eine #-Aufwertung ausgerüstet hast, kannst du deine Primärwaffen nicht verwenden. Dafür darfst du mit #-Sekundärwaffen auch Ziele außerhalb deines Feuerwinkels angreifen.
Lone Wolf(Einsamer Wolf) => Wenn keine freundlichen Schiffe in Reichweite 1-2 sind, darfst du beim Angreifen und Verteidigen 1 gewürfelte Leerseite neu Würfeln.
Stay on Target(Am Ziel bleiben) => Nach dem Aufdecken des Manöverrads darfst du ein anderes Manöver mit gleicher Geschwindigkeit auf deinem Rad einstellen. Dieses Manöver wird wie ein rotes Manöver behandelt.
Leebo[Crew] => Aktion: Führe als freie Aktion einen Schub durch. Dann erhälst du 1 Ionenmarker.
Dash Rendar[Crew] => Du darfst auch angreifen während du dich mit einem Hindernis überschneidest. Deine Schussbahn kann nicht versperrt werden.
Lando Calrissian[Crew] => Aktion: Wirf 2 Verteidigungswürfel. Dein Schiff bekommt 1 Fokusmarker für jedes # und 1 Ausweichmarker für jedes #.

**Comment by strikegun** [comment]
Denke ich habe die ÜBersetzung umgesetzt. Können dieses Issue schliessen?

**Comment by strikegun** [comment]
can be closed
