### ISSUE TITLE
VT-49 Decimator German Text

### ISSUE THREAD

**Issue by Barlmoro** [geordanr/xwing#136]
Patrol Leader (Patrouilenführer)
Captain Oicunn => Nach dem Ausführen eines Manövers nimmt jedes feindliche Schiff, das du berührst, 1 Schaden
Commander Kenkirk => Wenn du keine Schilde und mindestens 1 Schadenskarte hast, steigt deine Wendigkeit um 1.
Rear Admiral Chiraneau (Konteradmiral Chiraneau) => Wenn du ein Ziel in Reichweite 1-2 angreifst, kannst du ein # in ein # ändern.
Dauntless => Nach dem Ausführen eines Manövers, das zur Überschneidung mit einem anderen Schiff geführt hat, darfst du 1 freie Aktion durchführen. Dann erhälst du 1 Stressmarker.
Tactical Jammer(Taktischer Störsender) => Dein Schiff kann die feindliche Schussbahn versperren.
Ion Torpedoes(Ionen-Torpedos) => Angriff (Zielerfassung): Gib deine Zielerfassungsmarker aus und lege diese Karte ab, um mit dieser Sekundärwaffe anzugreifen. Triffst du, erhalten alle Schiffe in Reichweite 1 des Verteidigers und der Verteidiger selbst je 1 Ionenmarker.
Intimidation (Furchteinfössend) => Die Wendigkeit feindlicher Schiffe sinkt um 1, solange du sie berührst.
Ruthlessness (Erbarmungslos) => Nachdem du mit einem Angriff getroffen hast, musst du ein 1 anderes Schiff in Reichweite 1 des Verteidigers (außer dir selbst) wählen. Das Schiff nimmt 1 Schaden.
Ysanne Isard => Wenn du zu Beginn der Kampfphase keine Schilde und mindestens 1 Schadenskarte hast, darfst du als freie Aktion ausweichen.
Mara Jade => Am Ende der Kampfphase erhält jedes feindliche Schiff in Reichweite 1, das keine Stressmarker hat, einen Stressmarker.
Fleetofficer (Flottenoffizier) => Aktion: Wähle bis zu 2 freundliche Schiffe in Reichweite 1-2 und gib ihnen je 1 Fokusmarker. Dann erhälst du 1 Stressmarker.
Moff Jerjerrod => Wenn du eine offene Schadenskarte erhälst, kannst Du diese Auswertungskarte oder eine andere #-Aufwertung ablegen, um die Schadenskarte umzudrehen(ohne dass der Kartentext in Kraft tritt)

**Comment by strikegun** [comment]
erledigt,
can be closed
