### ISSUE TITLE
Reading QR code

### ISSUE THREAD

**Issue by dmborque314** [geordanr/xwing#144]
Hi!
I'm trying to read the QR code and I get the data, but I am unable to unzip them.
I am working in javascript and after trying several zlib libraries I always get errors: Incorrect header, invalid code lengths set....

I don't kown if you could provive me some hint on how to do it, or give the possibility to generate unzipped QR codes.
Greetings!

**Comment by geordanr** [comment]
I haven't actually tested the zlib'd QR code, so it's very possible that I've done it wrong; will look into it.
