### ISSUE TITLE
Feature Request: Add specific cards to "your collection"

### ISSUE THREAD

**Issue by Fenris78** [geordanr/xwing#145]
Hi, love your X-Wing squad builder!

Wondering if it would be possible to add a way to include cards bought/traded outside of the ship expansions? I've bought several cards from ebay, and it would be really useful to have them not show "you cannot field this list with your collection".

Many thanks :)

**Comment by geordanr** [comment]
This is a good idea but will take some time to implement; hopefully I can start on this once other things die down (I have some busy weeks coming up).
