### ISSUE TITLE
Print issue in Chrome

### ISSUE THREAD

**Issue by HippySi** [geordanr/xwing#147]
Using Chrome (Win 8.1), when I print in fancy mode, the preview looks OK, but when I actually go to print it, the page is long and thin. 

If I use the system print dialog, the paper is set to envelope (instead of my default A4). However, if I change the paper size, the content is not resized to fit - it is way too small (about A4 width) and centred on the page which doesn't look right at all.

Tried it in Torch and it works fine - it was top aligned and stretched to fill the page width.

**Comment by geordanr** [comment]
Strange.  I'm not sure how much control I have over what paper size the browser (or possibly the print driver) thinks it should be rendering to...

Bunch of questions incoming:

- Do any other sites print abnormally?
- Does this happen only in Chrome?  (I.e., try IE/Firefox)
- What about printing to PDF?
- Is it only fancy mode that suffers from this?

**Comment by HippySi** [comment]
Ah, just tried printing from a different site and same problem, so its not something specific to your builder, and yes its only Chrome that seems to do this.
