### ISSUE TITLE
Fleet Officer has wrong text

### ISSUE THREAD

**Issue by Hinny** [geordanr/xwing#148]
"at range 1-2" instead of "within range 1-2". The actual card differs from the preview card. ("at" and "within" have different definitions according to the faq).

**Comment by Morgul** [comment]
The site has "within range 1-2", which agrees with the text on the card:

![screen shot 2015-01-17 at 1 24 07 pm](https://cloud.githubusercontent.com/assets/770655/5790227/3ff59758-9e4c-11e4-996d-342d2e590afe.png)

![fleet-officer](https://cloud.githubusercontent.com/assets/770655/5790238/954d63c0-9e4c-11e4-8e8f-e2ff55c304af.png)

I'm not sure where you're getting "at range 1-2"?

**Comment by Hinny** [comment]
From the real card...

**Comment by Hinny** [comment]
Fleet Officer.jpg
https://docs.google.com/file/d/0B0dD5k8AOOx2cHpkVmpHb0FsLVE/edit?usp=docslist_api

**Comment by Morgul** [comment]
Interesting. It seems most of the people online are using the version from fantasy flight's site (the post initially previewing the VT-49:

http://www.fantasyflightgames.com/ffg_content/x-wing/news/wave5/fleet-officer.png

There is also, near as I can tell, no errata about this card, and I am finding quite a mix of people quoting the text as both 'within' and 'at'. I think this is worth posting on the FF forums, and see if we can get some clarification.

I wil also check my cards when I get home tonight, and see which my physical copy says.

**Comment by Hinny** [comment]
I'm not sure if i

**Comment by Hinny** [comment]
I'm not sure if I can take credit/blame for this change a but I posted on this subject when it was previewed and :-)

http://community.fantasyflightgames.com/index.php?/topic/108818-fleet-officer-within-range-vs-at-range/

**Comment by Hinny** [comment]
Sorry for that...  my phone bugged out

**Comment by geordanr** [comment]
Confirmed that it's "at" on my physical card, and there is no errata for it, so I'll correct it.
