### ISSUE TITLE
Show weapon attack/range data in fancy printout

### ISSUE THREAD

**Issue by geordanr** [geordanr/xwing#154]
@wffurr could you look into some good formatting for this?

**Comment by wffurr** [comment]
Sure!  I didn't test a list with a secondary weapon.  I see that the data is missing now.  I'm sure I can find a way to add it in nicely.

**Comment by wffurr** [comment]
Still working on the design.  I have a bunch of experiments.

I think what I like best is the most compact.  Move card name to the top left, then put the numeric stats on the right with no icons:

![screenshot 2015-01-23 19 27 34](https://cloud.githubusercontent.com/assets/519506/5885171/f9c90f8c-a335-11e4-9795-362e343a4c7a.png)

Other ideas I've tried...

![screenshot 2015-01-23 19 08 51](https://cloud.githubusercontent.com/assets/519506/5885009/6881af40-a333-11e4-917c-9f7769af76ed.png)

![screenshot 2015-01-23 19 24 08](https://cloud.githubusercontent.com/assets/519506/5885143/756b6b18-a335-11e4-91b3-ec38143cd43c.png)

**Comment by geordanr** [comment]
I like the attack icon; it might not be clear that it's an attack value when printed in black and white.  I think the range is fairly clear, and doesn't need to say "Range" next to it.

**Comment by armoredgear7** [comment]
I think we need the attack icon, and the black & white issue is solved if we use the vector one in the latest x-wing-symbols font I just sent you.

**Comment by geordanr** [comment]
I've added the new fonts to the [xwing-miniatures-font](https://github.com/geordanr/xwing-miniatures-font) package; I'll switch over to using those and will update master soon with that (gotta eat lunch first).

@wffurr if you want a head start do a `bower update xwing-miniatures-font` to update it on your end so you can start using the symbols.

**Comment by geordanr** [comment]
I just pushed changes to master that use icons for everything, like attacks and stuff.  So you can now do

```html
<i class="xwing-miniatures-font xwing-minatures-font-attack"></i>
```

and it will have the background set and stuff.  Feel free to mess with the styling to make it better; this was just a first pass.

**Comment by wffurr** [comment]
Got the new fonts, looks pretty slick.  Thanks @armoredgear7 !

I will work on making color / B&W an option for printing.  I mis-use the color lasers at work for my lists.

So here's a display with the icon, no "range" wording, and with the correct placement.  I also re-did some of the alignment using inline-block and vertical-align: middle, which is more robust.

Fancy web display:
![screenshot 2015-01-25 18 15 49](https://cloud.githubusercontent.com/assets/519506/5893766/b8d6b26a-a4be-11e4-8004-0bb99ed08ff3.png)

Chrome in print emulation mode:
![screenshot 2015-01-25 18 17 23](https://cloud.githubusercontent.com/assets/519506/5893769/c18326aa-a4be-11e4-9aae-1ff06769e071.png)

PDF: https://www.dropbox.com/s/qsh0e5abr41czpr/Secondary%20Weapon%20Test.pdf?dl=0

If this is good, I'll send in a pull request.

**Comment by geordanr** [comment]
Looks good!

![Do it](https://i.imgur.com/hoBbGBb.png)
