### ISSUE TITLE
Feature Request: Support for owned expansions

### ISSUE THREAD

**Issue by aapel0987** [geordanr/xwing#166]
First off I would like to say that this tool is awesome, thank you. Secondly I would be astounded if I was the first to suggest this feature, but I would like to add my voice to those requesting it; So here goes:

To say it concisely, I would like to have a option to have the tool prevent me from building squads that I cannot actually build based on the number of core sets and expansions that I own.

I would like to be able to put in the number of each expansion that I own on a page, and then when I go to the squad builder page only be able to select ships/pilots/upgrades in a configuration that I can actually achieve based on what I own. For example, if I only own 2 core sets and one X-Wing expansion, and nothing else, then in the rebel page I would only be able to build a squad using 3 X-Wings, only have pilots from those sets(IE I cannot use Porkins). I would not have access to any Y-Wings, etc. Upgrades would also be limited, preventing me from putting out more of them than I own.

Hopefully this was clear, and thank you for reading,
Alex

**Comment by elistevens** [comment]
Pretty sure this exists via the "Your Collection" link. It's on the right side, in the blue bar, and shows up when you're logged in.

**Comment by geordanr** [comment]
As @elistevens noted, it sounds like what you're looking for is already supported, but you'll need to be logged in.

Note that it doesn't *prevent* you from adding ships/upgrades you do not already own; instead it warns you.  (After all, you could borrow, say, a Predator card from someone.)

Closing issue; please reopen if the current implementation does not meet your needs.
