### ISSUE TITLE
Personal Collection?

### ISSUE THREAD

**Issue by jcoprsito** [geordanr/xwing#168]
Is it possible to update the tool to allow users to store their collection?  This way we can create lists with exactly what cards/ships we own instead of having to sort it out.

**Comment by armoredgear7** [comment]
This feature exists, although only on a per-expansion basis.
![screen shot 2015-02-24 at 4 12 23 pm](https://cloud.githubusercontent.com/assets/9486041/6359314/29256730-bc40-11e4-927d-1853253e88de.png)

**Comment by geordanr** [comment]
Closing this issue as the feature already exists.  Please reopen if the current feature does not satisfy your needs.
