### ISSUE TITLE
Guri & Virago

### ISSUE THREAD

**Issue by oneowhat** [geordanr/xwing#174]
Unable to add the title 'Virago' to Guri (PS 5).

Card text: 'You cannot equip this card if your pilot skill value is "3" or lower.'

**Comment by geordanr** [comment]
I am able to do so:

https://geordanr.github.io/xwing/?f=Scum%20and%20Villainy&d=v3!s!101:-1,-1:16:-1:U.-1,U.-1

Virago is unique; was it on another ship (Xizor) when you tried to add it to Guri?

**Comment by oneowhat** [comment]
Oops.. didn't realize that was a unique card. Here I thought I was being
helpful.

**Comment by geordanr** [comment]
Heh, no worries!
