### ISSUE TITLE
Printouts have a black title (missing text) with firefox browsers

### ISSUE THREAD

**Issue by strikegun** [geordanr/xwing#178]
If you print a squad build with the firefox browser, the title text of the squad is missing.

Issue mention over a facebook group.

**Comment by geordanr** [comment]
Is this only happening with Firefox?

Does it matter if the "Print Color" option is used?

I've noticed this happening also but I don't know the exact conditions to replicate.  @wffurr do you know what might be causing this?

**Comment by wffurr** [comment]
Reproduced in Firefox 35 on Mac.  Works in Chrome and Safari on Mac.

Amusingly, using `media emulate print` looks fine, but saving to PDF or printing shows the error.

![sample screen shot 2015-03-05 at 10 21 21 am](https://cloud.githubusercontent.com/assets/519506/6507642/6729f6e4-c321-11e4-8a87-d9f1a0e8e3b9.png)

**Comment by llanion** [comment]
Noticed this happening but didn't realize it was Firefox until today. Chrome prints the title (and faction symbol!) Firefox does not. 

Reproduced Firefox 45, Windows (and previous versions that I cannot name).

**Comment by geordanr** [comment]
Try turning on background colors and images in print options (I don't have a Windows box handy so I don't know exactly what or where the settings are).

**Comment by llanion** [comment]
That resolves the issue. 
Settings in Windows are either File, Page Setup, "Print Background (colors & images)" or the Firefox menu button, Print, Page Setup, "Print Background (colors & images)".
