### ISSUE TITLE
Scum & Villany: Most Wanted Ship counts

### ISSUE THREAD

**Issue by keithmcg** [geordanr/xwing#182]
My collection lists 1 Y-wing and 1 Most Wanted set owned, but the builder starts complaining if I try to field two Scum Y-wings, which the box has the parts to do so (as long as you own the model). 

I realise the interaction is going to be a mite tricky here, but it's probably worth tracking, if possible?

**Comment by geordanr** [comment]
It's working for me; can you send a permalink to the list that doesn't work with 1 Most Wanted and 1 Y-Wing?

**Comment by keithmcg** [comment]
OK, after trying again, that problem seems to have disappeared once I
loaded it up here. Possible was an error in my collection.
New one, more repeatable: Most Wanted comes with 2x R4 Agromech; it's
acting like I only own one. Simpler problem?
