### ISSUE TITLE
Extra spanish translation

### ISSUE THREAD

**Issue by Kharnete** [geordanr/xwing#185]
I've noticed there are lots of new stuff without translation, or even missing (Autoblaster turret, i.e.) after checking the Spanish cofee file.

I've seen similar proposals for other languages, so I guess it wouldn't be a problem to give you a hand on this :P. Should I submit a pull request with all the changes as you recommend in another thread? I've never tried to mess on github, but after checking around a bit it seems pretty intuitive.

**Comment by geordanr** [comment]
Yes, please!
