### ISSUE TITLE
No title slot on several ships (Spanish version)

### ISSUE THREAD

**Issue by Kharnete** [geordanr/xwing#189]
I've just noticed that several ships with existing Titles doesn't actually have the slot to equip them. I believe the reason is the new translated names on most of them, but there is also the Y-wing which was already translated. The ships are:

-Y-wing (both Rebel and Scum)
-Aggressor
-StarViper
-M3-A Interceptor
-VT-49 Decimator

**Comment by geordanr** [comment]
Still need the actual translations, but at least the stubs are there.
