### ISSUE TITLE
Mobile export

### ISSUE THREAD

**Issue by jwood8205** [geordanr/xwing#196]
I loved your squad builder largely because I could use it easy on iphone. But the new changes that added individual ship pt totals breaks it. I used to take a screen shot of the squad in txt view for easy access and sharing. Suggest adding a "save to mobile" feature that makes it easy to save a screen shot of squad lists. Thanks!

**Comment by geordanr** [comment]
I fixed the formatting so the ship total line doesn't take multiple rows.  Let me know if this works for taking mobile screenshots; if it doesn't I can just hide the ship total in mobile mode so it acts like it did in the past.

If the fix works for you, close this ticket.  Thanks!

**Comment by jwood8205** [comment]
That's good thanks! A way to hide ship totals as an option might be cool too, but this works!
