### ISSUE TITLE
Printing menue glitch

### ISSUE THREAD

**Issue by IanGlascock** [geordanr/xwing#213]
When print preview window appears, Half of the line reading "Print Color" is cut off by the bottom of the screen. I presume that the buttom to print is below that, however I can't access it as I can only scroll down the squad list and not the print controls. Perhaps it is a screen resizing issue. 

I am running this on a 13 inch Macbook Pro  OS X 10.10.4.

**Comment by geordanr** [comment]
This is a duplicate of #203
