### ISSUE TITLE
New core pilots! 

### ISSUE THREAD

**Issue by vonmonkhouse** [geordanr/xwing#220]
http://imgur.com/a/5TvSr

**Comment by geordanr** [comment]
I'm going to add these on a branch but not publish it on the public builder until it's been verified/released.

**Comment by geordanr** [comment]
Also, we don't know what the deal is with factions.

**Comment by vonmonkhouse** [comment]
Sounds good.

**Comment by tnels** [comment]
We do now! http://imgur.com/a/TNJiY#0

**Comment by geordanr** [comment]
Yeah... adding support for that in my private branch, along with the rest of the cards and stuff (including Tallon Roll).

Need to fix up tests, though, which got broken by all this mess.

I still won't update the public builder until the embargo is lifted.

**Comment by tnels** [comment]
Cant wait. :) Will be even better when I can actually fly them!

**Comment by geordanr** [comment]
Added.
