### ISSUE TITLE
Ep VII ships?

### ISSUE THREAD

**Issue by kdubbw** [geordanr/xwing#223]
Hey just was wondering if you were planning on putting in the ships and upgrades that have been spoiled from the new core set into the squadron builder. Kudos on the great squad builder! Only one I use!

Thanks. 

Feel free to email me with a reply, but no need to either. Just curious and want to get to squad building with what has been spoiled! :)

Kdubbwadsworth@gmail.com

Edit: Just saw your message on the other post regarding this issue. Sorry for double posting! Looking forward to having it in there once FFG gives us the info themselves!

**Comment by geordanr** [comment]
Duplicate of #220
