### ISSUE TITLE
German translation Wave VII & Raider

### ISSUE THREAD

**Issue by Necrogoat** [geordanr/xwing#227]
Will there also be aigan a german translation for the wave VII and the Raider?

**Comment by geordanr** [comment]
Hopefully, if someone contributes the translations.

**Comment by Necrogoat** [comment]
Hm i can send you the German text from the cards if you want/need. But I have no time before tomorrow evening or during monday

**Comment by geordanr** [comment]
Sure, just send them when you can.

**Comment by Necrogoat** [comment]
Hi

 

I hope this will be fine for you in this way and I think it should be complete now. If there is something still missing, feel free and tell me.

 

Greetings from Salzburg/Austria, 

Roland

 

Von: Geordan Rosario [mailto:notifications@github.com] 
Gesendet: Mittwoch, 9. September 2015 07:41
An: geordanr/xwing
Cc: Necrogoat
Betreff: Re: [xwing] German translation Wave VII & Raider (#227)

 

Sure, just send them when you can.

—
Reply to this email directly or view <https://github.com/geordanr/xwing/issues/227#issuecomment-138790836>  it on GitHub.  <https://github.com/notifications/beacon/ANIhfMGtIfCIvdc-y-3yFYJII2GuO_sqks5ov73wgaJpZM4F4aZM.gif> 



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus

**Comment by geordanr** [comment]
GitHub doesn't handle email attachments; you'll have to put the file somewhere I can download it, or put the contents into gist.github.com and send me the link.

**Comment by Necrogoat** [comment]
Hey

Here is the link to my dropbox, so I think it should work now. Let me know if you need something.

https://www.dropbox.com/s/e72ug86b7vsk0e3/%C3%9Cbersetzungen%20X-Wing%20Wave%207.docx?dl=0

Cheers

 

Von: Geordan Rosario [mailto:notifications@github.com] 
Gesendet: Donnerstag, 10. September 2015 09:12
An: geordanr/xwing
Cc: Necrogoat
Betreff: Re: [xwing] German translation Wave VII & Raider (#227)

 

GitHub doesn't handle email attachments; you'll have to put the file somewhere I can download it, or put the contents into gist.github.com and send me the link.

—
Reply to this email directly or view <https://github.com/geordanr/xwing/issues/227#issuecomment-139135458>  it on GitHub.  <https://github.com/notifications/beacon/ANIhfB79YyDwOGk0DMUZLP7B_k77vsSEks5owSSygaJpZM4F4aZM.gif> 



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus

**Comment by strikegun** [comment]
I am now translating the cards-de.coffee, so stay tuned. done almost

**Comment by strikegun** [comment]
My pull request is submitted. test was success
