### ISSUE TITLE
Integrate collection with card browser

### ISSUE THREAD

**Issue by errlarson** [geordanr/xwing#247]
If you integrated the collection data with the card browser data, you could create a view of a person's x-wing collection where they could see how many of each pilot and upgrade card they own.

One idea would be to add a new sort to the card browser such as "Type (by # owned)" that would display the # of copies of each card you own (instead of the point cost).

**Comment by errlarson** [comment]
sorry, should have read previous requests first.  This is a duplicate of #219

**Comment by geordanr** [comment]
I'll add the sort option to #219
