### ISSUE TITLE
Login doesn't work

### ISSUE THREAD

**Issue by mkrannich** [geordanr/xwing#250]
I tried to log in via google and twitter (I don't have a facebook account). With google a new window for oauth is opend, closed, refresh and nothing changed. With twitter the same.
I am using chrome. I tried firefox and got same behavior.

**Comment by geordanr** [comment]
I am unable to reproduce this problem.  Does this happen for you on all machines?  Does it happen when you use Chrome's Incognito Mode or Firefox's Private Browsing Mode?

**Comment by mkrannich** [comment]
Now at home I tried again in chrome normal and incognito mode and get same error. Then I used Edge in windows 10, oauth via google, no problem. :-/

**Comment by mkrannich** [comment]
In network monitoring I see only one entry.
ping 
Request URL:https://yasb-backend.herokuapp.com/ping
Request Method:GET
Status Code:401 Unauthorized

**Comment by geordanr** [comment]
That's really bizarre... are you logged in as multiple users on Google?  Try logging out of Google and logging back in again, and then trying to log in via OAuth.

(Kind of running out of ideas here...)

**Comment by mkrannich** [comment]
I deleted complete browser cache of chrome. Maybe using google apps, but why twitter doesn't work, too?! Any way to log the oauth transaction?

**Comment by geordanr** [comment]
The next time this happens, send me the date and time (and time zone) and I'll see if it's in the logs.  Unfortunately Heroku only keeps the last 1500 log messages, which is only about a couple hours' worth but maybe it'll be enough.

I have no idea what could be causing this, and why it's working on Edge of all places.

Does it happen to you on mobile devices?  iOS/Android?

**Comment by mkrannich** [comment]
Android with chrome works. ...or worked yesterday.

Now auth has been broken. Check auth status needs a long time and later
with click on log-in nothing happens.

2015-10-22 3:46 GMT+02:00 Geordan Rosario <notifications@github.com>:

**Comment by geordanr** [comment]
There does indeed seem to be a consistent problem with the authentication backend.  I'm looking into it.

**Comment by geordanr** [comment]
I've restarted the Heroku dyno and it appears to be working again.  @mkrannich please close this issue if auth is resolved for you.

Maybe I need to upgrade the Heroku dyno to the next tier of service...

**Comment by mkrannich** [comment]
Edge works, chrome not. Installed new firefox and it works. :-/
Are there any browser settings known which block heroku?
Tried serveral times at 25th Oct 19:00-19:01 UTC.

**Comment by geordanr** [comment]
Ugh, that's super weird.  I'm using Chrome myself and am not seeing this issue.

Can you send me (via email to geordan at gmail) the IP you're coming from?  I can keep an eye out for it in the logs.

**Comment by mkrannich** [comment]
I found a solution. In my chrome settings I block third party cookies. I added yasb-backend.herokuapp.com to the exception list and the log in works.

**Comment by zacharyp** [comment]
Confirmed this in Safari as well.  Fixed by switching Privacy setting for Cookies and Website data to the "Allow from websites I visit" choice.
