### ISSUE TITLE
Advanced Targeting Computer XWS canonicalization error

### ISSUE THREAD

**Issue by randolphw** [geordanr/xwing#251]
Advanced Targeting Computer should canonicalize as "advancedtargetingcomputer," but is coming out "advtargetingcomputer" instead.

**Comment by geordanr** [comment]
Whoops, forgot to mark this as invalid.

By the [XWS canonicalization](https://github.com/elistevens/xws-spec/#canonicalization-rules) rules:

    1. Take the English-language name as printed on the card
    2. Check for special case exceptions to these rules (see below)
    3. Lowercase the name
    4. Convert non-ASCII characters to closest ASCII equivalent (to remove umlauts, etc.)
    5. Remove non-alphanumeric characters

The card text is "Adv. Targeting Computer" as seen [here](http://vignette2.wikia.nocookie.net/xwing-miniatures/images/1/1e/Adv-targeting-computer.png/revision/latest?cb=20141220112136)

Marking as invalid and closing.  There should be a bug filed against the XWS spec to correct the example.
