### ISSUE TITLE
Ship Cards dissappear in Firefox

### ISSUE THREAD

**Issue by ThisIsStupidGitHub** [geordanr/xwing#258]
It seems, when i open this site up for the first time, it works properly, however after i log in (using gmail in this case) the Pilot cards no longer show for any ship, even if i click on them, or add/change ships. This only started happening this weekend.

Also, its kind of crap I had to make an account on here, just to report this issue.

**Comment by geordanr** [comment]
I apologize for the trouble with reporting issues.  A full refund has been transmitted.  Best of luck using other builders in the future.
