### ISSUE TITLE
Individual cards in inventory

### ISSUE THREAD

**Issue by edrahil** [geordanr/xwing#259]
Can you add a feature to add individual upgrade cards to our inventory? With all the tournament packs starting to give it upgrade cards, it'd be nice to have an accurate stock of what I have

**Comment by geordanr** [comment]
This has been requested a lot lately (I'm guessing because of C-3PO, among others), so I'll start working on this soon.

**Comment by geordanr** [comment]
I wish I had more hours in the day.  I will work on this as soon as I can.

**Comment by edrahil** [comment]
no worries.  You're doing a great job.  Thanks for maintaining such an
awesome resource.


Daniel Thompson

**Comment by Kumagoro42** [comment]
It'll be great to have that feature, thank you very much!
While you're working on it, some thoughts on the kind of collection management I (and possibly others) would like it to cover.

While I've certainly just acquired single upgrade cards outside packs, and that should be easy enough to manage by just adding them to a specific list, I've also done more complex changes, like buying packs, keeping some of the cards and selling the ship. One example for all: I bought an Imperial Raider expansion, then I took 3 copies of the TIE/x1 title, 3 copies of the Advanced Targeting Computer, and the TIE Advanced model included and I sold them all. So I would like for my collection to be able to reflect that I now own an Imperial Raider expansion MINUS all that stuff.
(If it's too complex, though, I'll be just glad to be able to tell the builder I own a second Sensor Jammer without owning a second Lambda :)

**Comment by zacharyp** [comment]
Bravo!  This is an awesome addition to the builder

**Comment by Kumagoro42** [comment]
Awesome! Thank you!
It took me a minute to understand why Mods and Titles have separate entries. :)
