### ISSUE TITLE
Selecting Huge ship modification bug

### ISSUE THREAD

**Issue by Rydiak** [geordanr/xwing#261]
I am unable to select a modification in the drop-down box for huge ship modifications.  If I scroll down to the bottom of the drop-down box (where huge ship modifications show) and move my cursor over one of the selectable modifications the box immediately moves to the drop of the list.  This repeats over and over.  Browser is Chrome.

**Comment by geordanr** [comment]
This is unfortunately a bug with Select2, the library that provides the dropdowns.  It occurs when the first item is disabled.  I may end up just removing disabled items from the modifications list.

The workaround (for now) is to type a substring of what you're looking for in the search box (like "auto" for Automated Protocols) and press enter to select that.

**Comment by Rydiak** [comment]
Thanks, Geordan. That's what I've been doing so far to create lists, but
now that we have actual Huge ship mods it sounds like a good idea to remove
the non-selectable ones.

Love the site! Keep up the good work!
