### ISSUE TITLE
Ordnance Tubes?

### ISSUE THREAD

**Issue by Rydiak** [geordanr/xwing#263]
I imagine this is a pain to code, but are you planning to add Ordnance Tubes to huge ships?

**Comment by geordanr** [comment]
It's a real pain to code, because I didn't really implement huge ships properly.  It's gonna require some awful (and possibly not stable) hacks to do.  I'll see what I can cook up.

**Comment by Rydiak** [comment]
Can you just make it so when selected under Modifications it adds all the missiles and torpedoes as options into the hardpoint slot?

**Comment by geordanr** [comment]
Yeah, I can do it for huge ships that only have one part.  That's not so bad.

But if you put in on a Raider aft, it won't affect the fore of the ship -- at least not without hackery.

**Comment by Rydiak** [comment]
You really only need the Modification slot on the Aft anyways, since Huge ships still can only take one Modification.  Maybe link the Fore and Aft together as one virtual unit, since one should not be able to be added to a list without the other?

**Comment by geordanr** [comment]
Fixed for a single ship in https://github.com/geordanr/xwing/commit/e3428bc17a079e7318a3fa161687f97caa33dd4d

Linking multiple ships has been problematic (I've tried to solve it in the past).

**Comment by Rydiak** [comment]
Can you remove the upgrade cost of Ordnance Tubes on the Fore section?

**Comment by Rydiak** [comment]
Oh hey, selecting Ordnance Tubes messes with the Team upgrade slot.

**Comment by Rydiak** [comment]
And Cargo too! Both Team and Cargo get messed up on a section that has
Ordnance Tubes selected as a mod.

**Comment by Rydiak** [comment]
Crew, Team, and Cargo slots receive missile and torpedos as selectable upgrades when Ordnance Tubes is selected.

Additionally, could you make the Fore Ordnance Tube modification cost zero squad points?
