### ISSUE TITLE
Kudos!

### ISSUE THREAD

**Issue by MtnManiacX** [geordanr/xwing#269]
Hey, I wanted to send you a message about the X-Wing Miniatures squad-builder you've created. There was no 'contact' link so I'm doing it through the 'feature request' link. Anyway, I just wanted to tell you that you've done a fantastic job with this tool! The only reason I've gotten as deep into this game is because of your efforts and how easy it is to create, print, and play a squad now. I never would have gotten this involved if I had to shuffle through hundreds of cards every time I wanted to play. 

I also really appreciate how on-top of things you are! I see that you glean any little tidbit of information that Fantasy Flight reveals about new ships, pilots, cards, etc. I see you add new content the very moment it's available. My group LOVES this app and if you had a 'donate' link I'd do it!

Please keep up the awesome work, and THANK YOU for all your efforts! You rock!!

Sincerely,
-Eric A. Beasley, Lumberton, NJ
Hey, I wanted to send you a message about the X-Wing Miniatures squad-builder you've created. There was no 'contact' link so I'm doing it through the 'feature request' link. Anyway, I just wanted to tell you that you've done a fantastic job with this tool! The only reason I've gotten as deep into this game is because of your efforts and how easy it is to create, print, and play a squad now. I never would have gotten this involved if I had to shuffle through hundreds of cards every time I wanted to play. 

I also really appreciate how on-top of things you are! I see that you glean any little tidbit of information that Fantasy Flight reveals about new ships, pilots, cards, etc. I see you add new content the very moment it's available. My group LOVES this app and if you had a 'donate' link I'd do it!

Please keep up the awesome work, and THANK YOU for all your efforts! You rock!!

Sincerely,
-MtnManiacX (Eric), Lumberton, NJ

**Comment by geordanr** [comment]
Thanks for the kind words!
