### ISSUE TITLE
Bug report (selecting Bossk crew with YV-666 Bossk)

### ISSUE THREAD

**Issue by Merandil** [geordanr/xwing#271]
Dear Geordanr,

first of I really like the squad builder you put online, but i've stumbled upon a little bug.
When selecting the YV-666 (bossk) you can't select the Bossk crew card.

Kind regards,
Merandil

**Comment by elistevens** [comment]
Yo Dawg, I heard you like Bossk, so I put Bossk in your Bossk, so you can... Wait, no, equipping two unique cards (in this case, Bossk the pilot and Bossk the crew) that share a name (in this case, "Bossk") is illegal per the rules ("Unique Names" on page 19 of the TFA rules).

Sorry, Boss...k.

**Comment by geordanr** [comment]
Closing since this is intended behavior.
