### ISSUE TITLE
customize my collection

### ISSUE THREAD

**Issue by Gorgiasbcn** [geordanr/xwing#275]
Congratulations on your utility to manage x-wing play lists.

The improvement that I think is essential is to be able to add single cards in "My collection". Currently, the only way is indicating the expansion that you have acquired . Given the growing community of x -wing exchanging cards and pilots improvement , it would be advisable to add individual cards to " my collection".

Thanks for your attention.

**Comment by geordanr** [comment]
Duplicate of #259
