### ISSUE TITLE
B-Wing/E2, Sabine and bomb problem

### ISSUE THREAD

**Issue by kksuke** [geordanr/xwing#285]
When B-wing equips B-Wing/E2, Sabine and some bomb, permalink is hangs.

https://geordanr.github.io/xwing/?f=Rebel%20Alliance&d=v3!s!44:-1,-1,-1,-1,137:-1:11:U.166&sn=Unnamed%20Squadron

**Comment by geordanr** [comment]
Permalinks generated from now on should handle this correctly.

[Example](https://geordanr.github.io/xwing/?f=Rebel%20Alliance&d=v4!s!44:-1,-1,-1,-1:-1:11:U.166,U.24&sn=Unsaved%20Squadron)
