### ISSUE TITLE
Imperial Assault Carrier Expansion - Your Collection

### ISSUE THREAD

**Issue by nafgan** [geordanr/xwing#299]
It appears that when adding the Imperial Assault Carrier to your collection you are not credited with owning Cluster Bombs, Construction Droid, Ion Torpedoes, Cluster Missiles, or Homing Missiles. I may have missed an upgrade or two. Also, Cluster Bombs and Construction Droid are incorrectly flagged as unreleased. 

Thanks for the awesome builder!

**Comment by Kumagoro42** [comment]
Those are suspiciously the same upgrades that the Wikia page for the Assault Carrier were missing. I fixed that page myself after I bought a Carrier recently and found out there were more cards in there than expected.
