### ISSUE TITLE
Domain is missing in BBCode and HTML Code

### ISSUE THREAD

**Issue by cbmainz** [geordanr/xwing#306]
Hi, at the currend version the domain is missing in BBCode and HTML Code when exporting. It says in BBCode only:

`[url=/xwing/?f=Galactic%20Empire&d=...=Unnamed%20Squadron]View in Yet Another Squad Builder[/url]`

**Comment by geordanr** [comment]
Whoops.  Byproduct of my fix for middle clicking on tabs.  I'll look at it tonight.
