### ISSUE TITLE
QR code failure

### ISSUE THREAD

**Issue by alexininikovsky** [geordanr/xwing#309]
It does not appear that the QR code feature is working on my machine. (ubuntu 15.10, firefox 45)

**Comment by geordanr** [comment]
Make sure you have background colors and images turned on in your print options.

**Comment by elistevens** [comment]
This is what it looks like on OSX:

![screen shot 2016-04-01 at 11 56 26 am](https://cloud.githubusercontent.com/assets/138016/14217064/e8bc2d84-f800-11e5-9c65-111184f7b2bc.png)

**Comment by alexininikovsky** [comment]
that was the problem. Thanks for the prompt reply.
