### ISSUE TITLE
Missing Auxiliary Arcs

### ISSUE THREAD

**Issue by Kumagoro42** [geordanr/xwing#310]
Correct me if I'm wrong, but I believe the information about a ship's 360° primary arc or auxiliary arc is not currently given anywhere in the builder? I think it might find room next to the attack value, maybe.

**Comment by geordanr** [comment]
I can do what the cards themselves do and use special icons to denote special firing.  However we only have the turret attack icon; [once they're added](https://github.com/geordanr/xwing-miniatures-font/issues/10) I can have them show up for the appropriate ships.  I should be able to get turret done in the meantime.

**Comment by Kumagoro42** [comment]
That's great. Didn't think you wanted to actually bother with the icons.
