### ISSUE TITLE
Pilot stats does not come up after last program upgrade

### ISSUE THREAD

**Issue by jgrubka** [geordanr/xwing#318]
Also missile slect sometimes don't work

**Comment by geordanr** [comment]
I am unable to reproduce this error.  What browser and OS are you using?  You may have old JavaScript cached; try clearing your browser's cache and reloading.

If it still persists, please attach screenshots (of both pilot stats not coming up and the not working missile dropdown).

**Comment by Kumagoro42** [comment]
I'm using Opera 36 under Windows 10, and I see no error whatsoever.

**Comment by jgrubka** [comment]
It works fine on my iPhone but not on my iPad

**Comment by geordanr** [comment]
Rolling into #320
