### ISSUE TITLE
iPad problems

### ISSUE THREAD

**Issue by jgrubka** [geordanr/xwing#320]
Earlier I wrote that when I bring up the pilots the maneuvers aren't there and sometimes there's ability sheets are not there I found the problem only occurs on my iPads.   This started happening after your upgrade my iPhone works fine good as it always did

**Comment by polmoneys** [comment]
Can confirm on iPad (Mini) something is really wrong. 

Some info is missing (dials) but that's not critical, the main problem is with dropdowns as some upgrades and pilots can't be selected (appears to be random)

I've been using your squad builder since forever on a daily basis without experiencing this issue.

Sad, but looking for alternatives as I mostly build lists on my iPad at home with a glass of wine and cigarretes...

**Comment by geordanr** [comment]
I don't have an iPad but I asked someone else with one to verify and they were not able to reproduce.  But I don't believe it was an iPad mini, so it may be tied to the device resolution.

@jgrubka what model iPad do you have?

**Comment by audreybeth** [comment]
Does this happen both in portrait and landscape mode, or only in one mode?

**Comment by polmoneys** [comment]
both modes. Try to put missiles on Inquisitor or Tie bomber in order to reproduce it.

**Comment by geordanr** [comment]
Strange; I'm unable to reproduce it via emulation.  I'll try to acquire an iPad to reproduce it locally.

Just want to double check: this is still occurring after clearing Safari's browser cache?

Which version iPad?  (Is it Retina?)

Is it consistently failing?  I.e. if you reload the builder, are there specific steps that, every time, result in this behavior?  What are the steps?

Please attach a screenshot of the failed case.

**Comment by jgrubka** [comment]
It's happening on the iPad mini and the iPad version just before the iPad Air

**Comment by jgrubka** [comment]
I love your program and I don't want to change over to any other program thank you very much for helping

**Comment by polmoneys** [comment]
I should know better, just upgraded to latest iOS version + cleared cache and now selects/dropdowns works as usual. 

Thank you.

**Comment by geordanr** [comment]
@polmoneys good to hear!

@jgrubka does clearing the cache resolve the issue for you as well?

**Comment by jgrubka** [comment]
I did the latest download on my system and it cleared the problem.
Thank you for your help and for this wonderful product!
