### ISSUE TITLE
Feature request maybe?

### ISSUE THREAD

**Issue by somnicide** [geordanr/xwing#321]
I might also just be missing how to do this, but is there a way to print the ship dials on the list? I'm a pretty new player and being able to see all of the dials right there is really helpful and also, I like being able to hand the sheet to my opponents with the dial there for them to view.

Awesome product and loved hearing you talk about it on Hella Squadron!

Thanks!
Patrick

**Comment by geordanr** [comment]
Bumping this in priority as others have asked for this as well.  (I'm thinking of overhauling the print output in general, anyway, as there isn't an efficient space for the maneuver grid at the moment.)

Glad you enjoyed our beer-addled discussion!

Duplicates #195; updates will be tracked there.
