### ISSUE TITLE
Final Imperial Veterans preview.

### ISSUE THREAD

**Issue by cbmainz** [geordanr/xwing#322]
Hi, thanks for the update, but what about [Glaive Squadron](https://images-cdn.fantasyflightgames.com/filer_public/54/10/54107776-5fc5-4f03-b51f-9fa6e4c6ce78/swx52-glaive-squadron-pilot.png) and [Gamma Squadron Veteran](https://images-cdn.fantasyflightgames.com/filer_public/21/9a/219af081-356c-4aab-bb17-09644fb07b32/swx52-gamma-squad-vet.png)?

**Comment by elistevens** [comment]
[Works Great](https://geordanr.github.io/xwing/?f=Galactic%20Empire&d=v4!s!194:175,-1,-1:33:13:;191:20,-1,-1,-1,-1,-1:35:2:u.103,u.102&sn=Works%20Great) for me. Try refreshing / reloading the page?

**Comment by cbmainz** [comment]
Yes, but these ships do not appear.

**Comment by elistevens** [comment]
You're going to have to be more descriptive, since they appear for me. What
do you see when you click my link?

**Comment by cbmainz** [comment]
Ah, thy do not appear in the german version. With your link in the english version I can see them.

**Comment by cbmainz** [comment]
Or to be more precise, I can see the ship in the german version following your link, but if I open the german version of the squad builder thy do not appear.

**Comment by cbmainz** [comment]
Okay, I did a [pull request](https://github.com/geordanr/xwing/pull/324) for this issue.

**Comment by cbmainz** [comment]
Thanks, that was quick. And [x-wing.crowdapp.de](https://x-wing.crowdapp.de/) is also updated.
