### ISSUE TITLE
Add B Wing/E2 Title

### ISSUE THREAD

**Issue by relentless** [geordanr/xwing#326]
I think it used to be there, but it's not showing for me now.
![image](https://cloud.githubusercontent.com/assets/410632/14984125/11701e10-1139-11e6-86a5-0baed71fa507.png)

**Comment by elistevens** [comment]
[Works for me.](https://geordanr.github.io/xwing/?f=Rebel%20Alliance&d=v4!s!41:12,107,23,-1,-1:-1:11:U.25&sn=Unnamed%20Squadron)

**Comment by relentless** [comment]
Sorry, my mistake - I was thinking it was a title not a modification.
