### ISSUE TITLE
javascript:void(0) error in Firefox 46

### ISSUE THREAD

**Issue by muehf** [geordanr/xwing#329]
When I use the newest Firefox Version I get a javascript:void(0) error and a very annoying sound. I tried clearing cache and cookies, starting in save mode and made sure javascript was enabled. However the error and the sound stay. I find some hints pointing to a coding error, so could you please infestigate the issue. Thanks!

Kind regards

Frank

PS: Everything works fine in MS Edge

**Comment by elistevens** [comment]
Can you please post more info about the error? I'm on FF 46 and don't see any errors in the console.

**Comment by muehf** [comment]
If I hover over one of the drop-down menus or selecting a value I get a small info in the lower left hand corner saying javascript:void(0) (see screenshot). If I select an entry in any drop-down menu I get the anoying sound. Sadly I don't know how to provide you with more info as I'm no programmer. Could Firebug help?
![2016-05-19 00_48_51-](https://cloud.githubusercontent.com/assets/19438433/15377457/140d4ccc-1d5c-11e6-9017-6725d0ee52dc.png)

**Comment by muehf** [comment]
I used the web console and it tells there is an empty string in getElementById().
It also states there might be an issue with scroll linked effects (see https://developers.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects)
Sadly the exact error messages are in German so I don't post them here.

**Comment by geordanr** [comment]
Does this happen only on Firefox?  Does the problem occur in other browsers?

What are the specific steps required to reproduce the error?

**Comment by muehf** [comment]
I guess I fixed this by turning off the hardware accelaration for the graphics card in Firefox.
