### ISSUE TITLE
Heroes of the Aturi Cluster

### ISSUE THREAD

**Issue by allynb927** [geordanr/xwing#344]
Hi. Was wondering if you could create a new tab that opens up the ability to create a ship for the heroes of the Aturi cluster campaign.
Thank you very much. Love your app.
Allyn

**Comment by geordanr** [comment]
Sorry, but I have no plans to support HotAC.  It would be too difficult to remove the restrictions in place (as well as adding features like stacking pilot abilities) that are required to enforce tournament legality in order to support HotAC.

A separate builder would be necessary to support this.
