### ISSUE TITLE
Ship name on printed sheet

### ISSUE THREAD

**Issue by gmodos** [geordanr/xwing#370]
Please, put ship's name on printed sheet. Thx.

**Comment by geordanr** [comment]
Originally the full ship name was in the printout.

However, someone later pointed out that for many new players, the ship name wasn't useful -- they didn't know what an M3-A Interceptor was, and instead the ship icon was much more useful.  So I switched to that.

Also, some ship names are really long, and won't fit (e.g. "Lancer-class Pursuit Craft").

**Comment by gmodos** [comment]
The ship icon is a good idea, but it is too small for recognizing. Printing in A4 size, there's enough space for ship name ([link](https://drive.google.com/file/d/0B8SW9PZmA7fBVjd0d19paWxpa1U/view?usp=sharing
![print_ship_name_2](https://cloud.githubusercontent.com/assets/12628798/19694100/473111c4-9ade-11e6-9c49-39661c639b89.png)
)). My suggestion is a checkbox for printing ship name ([link](https://drive.google.com/file/d/0B8SW9PZmA7fBbFZVQ1QzMlkxeHc/view?usp=sharing)).

Another issue:
I've been working on Hungarian translation for a while. If you don't mind I'll commit it in 2 weeks.

**Comment by geordanr** [comment]
I added the ship name always, as I don't want to add another print option.
