### ISSUE TITLE
Internal Server Error on login

### ISSUE THREAD

**Issue by javiles1972** [geordanr/xwing#424]
Every time I attempt to log in I receive this error:

**Internal Server Error**

**Comment by geordanr** [comment]
Does this still occur if you try it in Incognito Mode (Chrome) or Private Browsing Mode (Firefox)?

If so, which authentication platform are you using (Google, Facebook, or Twitter)?  Roughly what date and time did the login failure happen?

**Comment by geordanr** [comment]
Also, when you receive the Internal Server Error, when does it happen?  When you choose one of the authentication platforms you should be prompted to log in or grant permission to use the application.  Do you ever see the login page?

What is the URL of the page that is giving the Internal Server Error?

**Comment by geordanr** [comment]
@javiles1972 @RICoder72 I think I found the problem; please try again and let me know if it resolves the issue.

**Comment by RICoder72** [comment]
I've made a few more attempts, these are my actions/results.

First, I cleared all cookies / browsing history / etc. to make sure I was going in clean.

Chrome - Click on Login.  The OAuth dialog comes up.  Clicked the Facebook button.  A new tab opened.  "Internal Server Error".  This is the URL in the address bar.

`https://yasb-backend.herokuapp.com/auth/facebook/callback?code=AQCEFlZrjz59ORr5yHn4a3tE4fbrUs2aF9MmmuEAceS2E3m4ut64QjSN5bYUQkBm7G7lkdv6v7nfhlwvj7PLU7iLPP1H_mtelMlnS7-miOrcFJcQUrNZ1z-Iy3skCUZ6QV1ziBM1g8s4h0Bi7CagbxaC8NNcZbamzKtgPFkTWa-n_ecltynXXfzptEXH5VdKiXYCc-EJhG15nccasetGngRB5j4s3GrZ8G8bpmtbbdJIvne3hSIxjX7K6HDpfXwOoQt91xKMAboRRS6wujGkV18TB1MTpieRtlb9nhtMRNkrW92ioh549cx8k365Xk0jzvI&state=6a132ff30134837fe3672876817670fa353966e32a7d1cd1#_=_`

Chrome Incognito - Same process, the only difference being the new tab had a facebook login screen.  I filled it out correctly, hit the button, "Internal Server Error".

Same results in Microsoft Edge if you're curious.

Is there any more debug information I can get for you?

**Comment by geordanr** [comment]
Definitely something going on in the backend, but I don't know how to trigger your exact problem.  I pushed up a possible fix; try logging in again.

**Comment by javiles1972** [comment]
I'm away on business and will check on Sunday. Thank you.

**Comment by RICoder72** [comment]
...and it worked.  Using Microsoft Edge fyi (which I doubt matters).

Keep up the good work man, the site is coming along very well.

**Comment by geordanr** [comment]
Closing this (I'm hoping the issue that was affecting @RICoder72 was also affecting @javiles1972); if not, reopen this bug.
