### ISSUE TITLE
Collection option not showing up

### ISSUE THREAD

**Issue by DrGerm** [geordanr/xwing#429]
Sorry, not sure how/where to figure this out.

I see YouTube videos where people use this list builder and are able to input your collection.

For me, there is no button (near the print and permalink buttons) to enter a collection.

I am logged in, tried with a Twitter account as well as with a Google account. Using Windows 10. Tried two different browsers (Chrome and Edge). I am accessing this on 3/27/2017 (I find no version number in the about).

Any ideas for me? Has this feature been removed?

Thanks!

**Comment by geordanr** [comment]
The feature is still there; can you attach a screenshot?

**Comment by DrGerm** [comment]
Weird, must be something with me, but idunno. Screenshot attached. Thanks!

![2017-03-28](https://cloud.githubusercontent.com/assets/243401/24390827/3fdcc65e-1359-11e7-92be-fa74e68f3dfe.png)

**Comment by geordanr** [comment]
Found a problem with the backend; I think I have a fix.  Try it again and let me know if you're able to get the collection dialog and save your collection details.

**Comment by DrGerm** [comment]
Cool. Yep. I see it now and entered some sets and it seems to show up as expected when creating squads. Thanks!
