### ISSUE TITLE
Collection won't save

### ISSUE THREAD

**Issue by squaredt** [geordanr/xwing#431]
The site won't save my collection despite many attempts

**Comment by geordanr** [comment]
Which OAuth provider (Google, Facebook, or Twitter) were you using?  Does it still occur if you use any of the other providers?

**Comment by squaredt** [comment]
I was using Google, I just tried Twitter and Facebook and they both do the
same thing.

Let me know if there is any other info you need to help

**Comment by geordanr** [comment]
@squaredt @apoupada what browsers are you using?  Are you having problems saving squads also, or is it just collections?

Also please note what time (and time zone) you're having these problems; I'm trying to find errors in the logs, but I'm having trouble finding any errors associated with failed saves so having timestamps will help me figure out what's going on.

**Comment by apoupada** [comment]
I'm using chrome. It's only my collection, the squad list is saved. Today at 2:20 EST. I added my ships and cards to my collection, after i closed the tab i came back 30 seconds later and it was gone. I think because there is no save button it might be causing the issue.

**Comment by squaredt** [comment]
2:41 pm eastern time added B-wing expansion to my collection it appeared as
ships I own when adding to squad, then after refresh still at 2:41 pm
eastern time the B-wing expansion was no longer in my inventory and ship
was not shown as owned when adding to squad

Squads save perfectly

I am using chrome 56(most current) for Android 7.1.1 on a Google Pixel
device

**Comment by geordanr** [comment]
I have some idea of what's going on, but I won't have time to look into it until later tonight.

Are these new collections (i.e. no ships were in the collection previously), or was there data in the collection and now it won't update?

Also, when you change one of the values in the collection and wait a couple seconds, do you see a message by the "Close" button that says "Collection saved" or is there a different message?  Or is there no message at all?

**Comment by squaredt** [comment]
New collection

No message

**Comment by marcne** [comment]
Same happens to me in Safari and Chrome on Mac OS versions

**Comment by Buddhha** [comment]
Hi!
I'm using Chrome, with FB login.
Timestamp: CEST 01:45 2017-04-04
Squad saved perfectly.
No message at Close button.

**Comment by marcne** [comment]
Hi (extra info)
I'm using Chrome on Mac OS, with Google, FB or Twitter login.
Timestamp: 02:01 2017-04-04
Can't save collections

**Comment by geordanr** [comment]
I believe I've found the issue but I'm not sure if I've fixed it.  I added some extra log output when failures occur, so please try again and I'll see if it generates more information for me to work with.

**Comment by apoupada** [comment]
It seems to be working for me now, I even closed the page and waited 30 seconds and came back and it was there. Also after each time I added a new expansion or card the message "Collection Saved" appeared a second later, which it wasn't before. Thank you for fixing the issue, and thank you for this amazing tool! Makes creating lists so much easier.

**Comment by Buddhha** [comment]
Hi!
It seems that the probelm solved. Right now, I saw th "Collection Saved" text, and after a logut/login, the sets are visible.
Thanks for the fast help!

**Comment by squaredt** [comment]
Is also fixed for me

Thanks

Great tool, keep up the good work : )

**Comment by marcne** [comment]
Fixed! Thank you for the great tool you have created :)

**Comment by geordanr** [comment]
Fixed in 3a9ed576f1b9fccf86048bdbda11f5528523f567
