### ISSUE TITLE
Tie Advanced Prototype XWS name is wrong

### ISSUE THREAD

**Issue by kingargyle** [geordanr/xwing#434]
I ran into a problem with importing some XWS data from yet another squad builder and trying to cross reference that with the ship data files from xwing-data.  I had original opened the following issue at that project:

https://github.com/guidokessels/xwing-data/issues/86

However he pointed out that it appears to be a yasb issue.

yasb is setting the xws ship name to tieadvanceprototype, when it should be tieadvprototype.   See the issue linked above for the discussion.

This is causing some issues within the XStreamer application I use for creating the squad overlays on the Raven Squadron youtube videos when a Tie Advanced Prototype is shown, causing me not to be able to display the correct shield and hull values on import.

**Comment by geordanr** [comment]
Ugh... maybe not quite fixed yet.

**Comment by kingargyle** [comment]
Thanks will try it this weekend.
