### ISSUE TITLE
Bug for french Version

### ISSUE THREAD

**Issue by sirmaugan** [geordanr/xwing#437]
Hi, i am To organiser and i love your builder, sadly since a little time french version as issues (mainly (always) when the card aren't translated), can you correct it ? maybe i can help for the card text ?

**Comment by geordanr** [comment]
Since I don't have access to non-English translations, I rely on others to contribute fixes to translations.  Any help would be appreciated!

French translations are stored in here: https://raw.githubusercontent.com/geordanr/xwing/master/coffeescripts/cards-fr.coffee

You can make updates to it and either [make a pull request](https://help.github.com/articles/about-pull-requests/) (if you're comfortable with programming and using git and GitHub), or you edit that file and attach the updated file to a comment you make here.

**Comment by sirmaugan** [comment]
Ok thx, i will make that soon as possible, but it remain a problem i see in the file, that you let the English version of the card, but when you are in french somes cards (like All pilots from Rebels tie) stay empty

**Comment by geordanr** [comment]
Yeah; those were probably lazy copies on my part or things I forgot to put in.  :(

**Comment by sirmaugan** [comment]
That's made (what a F... work, all my respect for the job you have done!) i attach the file here because i'm not really comfortable with programming (but i will try to correct that for the next time), i think that would correct the issue whith title for Defender, Bomber and maybee for the Sabine' Tie (but not sure)
[cards-fr.coffee.txt](https://github.com/geordanr/xwing/files/919521/cards-fr.coffee.txt)
if i made errors, plz tell me !

**Comment by geordanr** [comment]
Thank you!

**Comment by sirmaugan** [comment]
Hi, thanks for this fast update... 
but it's have sommes problems i didn't see, so i have update the file for some:
[cards-fr.coffee.txt](https://github.com/geordanr/xwing/files/921625/cards-fr.coffee.txt)

and for the other:
extra munitions: the text isn't in the file and when it's chose in the builder the squadron value stuck
Glaive squadron are missing (in the file too) 
Gamma squadron Veteran are missing too 

so i think the missing code must be something like :

"Extra Munitions"
            name: "Munitions supplémentaires"
            text: ""Quand vous êtes équipé de cette carte, placez un marqueur "ordonnance" sur chaque carte d'amélioration %TORPEDO%, %MISSILE% ou %BOMB% équipé. Quand on vous demande de défausser une carte d'amélioration, vous pouvez défausser 1 marqueur ordonnance sur cette carte à la place."""

"Glaive Squadron Pilot":
            ship: "Défenseur TIE"
            name: "Pilote de l'escadron Glaive"

"Gamma Squadron Veteran":
            ship: "Bombardier TIE"
            name: "Vétéran de l'escadron Gamma"

But i didn't know if it's enough and if the place in the file matters...

**Comment by sirmaugan** [comment]
hi, i made a update with Wave XI and C-Roc
[cards-fr.coffee.txt](https://github.com/geordanr/xwing/files/1163676/cards-fr.coffee.txt)
can you make the update ? 
thx

**Comment by sirmaugan** [comment]
bug correction for light scyk: (omited "ship:" ligne)
[cards-fr.coffee.txt](https://github.com/geordanr/xwing/files/1185936/cards-fr.coffee.txt)

**Comment by geordanr** [comment]
For future fixes, please open a new issue so it's easier for me to find.  I close issues once fixes have been applied so I can keep track of what I have addressed and what I have not; it's easy for me to miss updates on issues that are already closed.

Also, when making edits please make sure you are using the [latest version](https://github.com/geordanr/xwing/blob/master/coffeescripts/cards-fr.coffee) of the file; I had added entries from Guns for Hire that I had to re-merge into your changes.

**Comment by geordanr** [comment]
There also seems to be some inconsistency with the indentation you're using (either with spaces or with tabs) which is making it difficult to merge these changes in.  Please only use spaces to indent, and match the indentation (4 spaces per level); otherwise, the file will not compile in CoffeeScript (which it isn't, currently).

**Comment by sirmaugan** [comment]
Ok, sorry for mistakes

Rémy Foret

De : Geordan Rosario<mailto:notifications@github.com>
Envoyé le :lundi 31 juillet 2017 20:05
À : geordanr/xwing<mailto:xwing@noreply.github.com>
Cc : sirmaugan<mailto:sirmaugan@hotmail.com>; Author<mailto:author@noreply.github.com>
Objet :Re: [geordanr/xwing] Bug for french Version (#437)


There also seems to be some inconsistency with the indentation you're using (either with spaces or with tabs) which is making it difficult to merge these changes in. Please only use spaces to indent, and match the indentation (4 spaces per level); otherwise, the file will not compile in CoffeeScript (which it isn't, currently).
