### ISSUE TITLE
Long-Range Scanners 

### ISSUE THREAD

**Issue by cbmainz** [geordanr/xwing#438]
Hi, 

I can't equip Long-Range Scanners to TIE/SE Fighters. Is this a bug or am I mistaken with the rule?

Cheers 
cbmainz

**Comment by geordanr** [comment]
Long Range Scanners requires that the ship have a torpedo and missile slot before you can equip it.

**Comment by cbmainz** [comment]
Ah, torpedo `and` missile not torpedo `or` missile. Thanx.
