### ISSUE TITLE
pictures

### ISSUE THREAD

**Issue by larky1960** [geordanr/xwing#440]
on (Yet another X-wing Miniature) web site, can you please add images of the ships? Right now when adding a ship to a build all you have is a pull down list of ship names. Pictures would really be helpful. I am new to X-Wing and am a very visual person. Please consider this. Also when I go to print my list it just pops up and asks me if I want to print in color? There seems to be no actual button to send to my printer.  Thank you for listening.

**Comment by geordanr** [comment]
Adding ship icons is a good idea; I'll do that.

Are you trying to print while on mobile?  Mobile printing is currently not supported.

**Comment by larky1960** [comment]
thank you for reading my letter and considering it.
Mark
