### ISSUE TITLE
Cannot authenticate using OAuth Facebook

### ISSUE THREAD

**Issue by xcschultzx** [geordanr/xwing#442]
This morning I am getting Authentication failed from multiple devices when trying to log in via the Facebook OAuth button (https://yasb-backend.herokuapp.com/auth/failure?message=invalid_credentials&origin=https%3A%2F%2Fgeordanr.github.io%2Fxwing%2F&strategy=facebook#_=_)

Any suggestions or is this a temporary issue?  Thanks!

**Comment by geordanr** [comment]
I think somehow the Heroku IP that was running the backend got blacklisted by Facebook.  I've restarted the backend and I think Facebook auth is working again; give it a try and let me know if it's working for you.  (It also failed for me, but now works after the restart.)

**Comment by xcschultzx** [comment]
Good to go thanks!!
