### ISSUE TITLE
Bring back permalink

### ISSUE THREAD

**Issue by JaxonEvans** [geordanr/xwing#453]
Apparently permalink has been removed, or isn't working. It was one of the best features of this squad builder, I'd recommend bringing it back

**Comment by geordanr** [comment]
The location bar now automatically updates, so you can just copy that.  The button is no longer required.

Duplicate of #452

**Comment by KingmanHighborn** [comment]
Where is the location bar then for those of us that are layman?

**Comment by elistevens** [comment]
The location bar is the place you'd copy the permalink URL from (unless you were always just right-clicking the permalink button like a barbarian):

Firefox: 
![screenshot from 2017-08-07 12-29-24](https://user-images.githubusercontent.com/138016/29042638-95cdfeae-7b6c-11e7-84e7-9a92fc04c45f.png)

Chrome:
![screenshot from 2017-08-07 12-28-55](https://user-images.githubusercontent.com/138016/29042640-9a52494e-7b6c-11e7-931d-4501e43a9b37.png)

Let me know if you aren't running firefox or chrome.

**Comment by KingmanHighborn** [comment]
I'm using Edge primarily.
