### ISSUE TITLE
Single Sign On with google oAuth not working

### ISSUE THREAD

**Issue by ManuelWittke** [geordanr/xwing#455]
Logging in with google Account does not lead to be logged in.
- Google Account are displayed
- Account can be choosen
- Google Window closes after choosing
- YASB still shows "log in". User is not able to load saved squads

Happens on 
- Windows 7, Chrome 58.0.3029.110 (64-bit)
- Mac OS 10.10, Chrome v. something (up to date)

Works fine on Mac OS 10.10 Safari (up to date)

Thanks for this excelent Squad builder!

**Comment by geordanr** [comment]
Does this issue still happen if you use Incognito Mode on Chrome?

**Comment by ManuelWittke** [comment]
I just tried incognito mode with chrome v58.0.3029.110 (64-bit). 
it still happens

**Comment by geordanr** [comment]
Unfortunately I only get a limited number of lines of log output from the backend, so I'll only be able to get more information about what's going on my side if I can get to it soon enough.  Try to trigger the error such that it happens during the day Pacific time and let me know here, and hopefully I'll be able to see what's going on in the logs.

Does this work in browsers other than Safari?

**Comment by ManuelWittke** [comment]
I just tried Firefox 53.0.3 (32-Bit) and it works fine.

I try with chrome for Mac May 31st .2017 10:00 PST

If helpfull I could maybe provide a teamviewer access.

**Comment by geordanr** [comment]
Were you able to reproduce the problem?  I haven't seen any errors in the logs.

**Comment by ManuelWittke** [comment]
I was staying late, I appologize.
I try now - 12:00

**Comment by geordanr** [comment]
I don't see any errors in the backend; I see several google_oauth2 connections and they all appear to be successful.

Given that I don't see any errors on my (or Google's) end, and that it works for you on other browsers except Chrome, I'm suspecting that there's some kind of problem in Chrome specifically.  I'm not sure what I can do to help with that, though.

**Comment by ManuelWittke** [comment]
And since no one else committed to this issue I would agree with you. 
Still weird that I experience the problem with Chrome Mac and Windows and IE. 
Hopefully a future browser update will help.
Thank you very much for the time you are investing in this very very cool tool. :-)

**Comment by geordanr** [comment]
I have a hunch as to what's going on, since this problem just happened to me.

Do you have third-party cookies disabled, or have an extension that somehow blocks cookies (like [Privacy Badger](https://www.eff.org/privacybadger)?  That could cause the symptoms you're seeing.  If so, you need to whitelist `yasb-backend.herokuapp.com` so that the authorization cookies can make it through.

**Comment by ManuelWittke** [comment]
YES! That helped.
I added [*.]yasb-backend.herokuapp.com/ to the exceptions for third party cookies in Chrome.
Finally, no more browser-switching.
Thank you!

**Comment by ManuelWittke** [comment]
Issue of cookie-blocking within browser or browser add-on
Allow cookies from third-party-sites or add exeption for [*.]yasb-backend.herokuapp.com/
