### ISSUE TITLE
Add C-ROC PLEASE

### ISSUE THREAD

**Issue by analogben** [geordanr/xwing#458]
Please add all items related to the list of the C-ROC cruiser. I was expecting this to be done because of showing previews for releases farther out from now such as the Tie Aggressor.

**Comment by elistevens** [comment]
What have you noticed that's missing?

**Comment by geordanr** [comment]
Note that huge ships and their upgrades don't show up unless you select "Epic" or "Team Epic" from the dropdown at the top.

**Comment by analogben** [comment]
I can't add the ship to my collection at all. Which means I can't see/use
the upgrade cards when making standard squadrons. Thanks

**Comment by geordanr** [comment]
Updated the manifests to include the contents of the C-ROC, which should allow you to add it to your collection now.

**Comment by analogben** [comment]
Thanks ...impressed with the speed!
