### ISSUE TITLE
Advanced SLAM ...

### ISSUE THREAD

**Issue by wilder3jw** [geordanr/xwing#460]
... is not in the individual "Collection" components.

**Comment by geordanr** [comment]
It's showing up for me:

![advslam](https://user-images.githubusercontent.com/334985/26998114-02ad4bda-4d35-11e7-9da4-6a5dcc64087d.png)

**Comment by wilder3jw** [comment]
That's weird.  I have never seen it before subdivided into groups -- "Expansions" and so on.  It was all just grouped together.  In order -- Expansions first and so on, but all in the same list.  I didn't have the headings until I reloaded the page.
 Jeff - wilder_jw@yahoo.com

"And anyways, I'd rather listen to Coltrane | Than go through all that shit again."
