### ISSUE TITLE
Feature Request - HOTAC specific builder

### ISSUE THREAD

**Issue by lazyj-bam** [geordanr/xwing#464]
I may be putting this feature request in the wrong spot - if so I apologize. But I was wondering if there could be a tab created for "freeform" squad building. Something that aligns with Heroes of the Aturi Cluster comes to mind specifically, but maybe instead of trying to apply a specific system's logic and rules it could just be a tab that allows building without restrictions. For example, create an X-wing and associate 2 elite talents and 3 modifications to it, then sum up the points and have a nice printable to help collect all the card text in one output. Even just doing this for a single ship at a time would be nice, and I can't find another squad builder that does anything like this. Appreciate all the hard work you put into this builder - it's really a great tool!

**Comment by geordanr** [comment]
This actually would require writing and reimplementing a completely separate builder; I am not planning to support that (or other freeform/differently-restricted rulesets).
