### ISSUE TITLE
Title: royal guard with saber squadron

### ISSUE THREAD

**Issue by caillouvs** [geordanr/xwing#468]
Hello guys, I just discover your website, this is AWESOME!

I saw that something is not working properly. With the TIE interceptor, we should be able to put the title: Royal guard with the pilot "saber squadron pilote" because he is a 4.

could you check it out? thanks!

**Comment by FreakyDug** [comment]
You've misread the upgrade ;) 

> You **cannot** equip this card if your pilot skill value is **"4" or lower**.
