### ISSUE TITLE
Adaptability upgrade card

### ISSUE THREAD

**Issue by MichaelForwerck** [geordanr/xwing#473]
Unlike "Veteran Instincts", equipping "Adaptability" isn't being reflected when viewing your pilots new PS for purposes of equipping other restricted upgrade cards.  

Example:  Trying to equip the "Black One" title card (requires 7 or higher PS) to a T-70 pilot with a 6 or lower natural pilot skill.  If I equip "veteran instincts" to "Snap Wexley" (natural PS of 6), the system updates his PS to 8, and then allows equipping "Black one" title card.  If I equip "adaptability" to the same pilot (making his PS 7 [or 5, for that matter]), "black one" title card remains shaded and unavailable despite the pilot now qualifying for it.

**Comment by geordanr** [comment]
According to the [!Dual Card reference card](https://vignette1.wikia.nocookie.net/xwing-miniatures/images/e/ea/DualCardPlaceHolder.jpg/revision/latest/scale-to-width-down/220?cb=20160311003806) the card text of Adaptability doesn't take effect until the Place Forces step, which occurs during list building.  Therefore, it can't grant the plus (or minus) effect on pilot skill in the list builder.
