### ISSUE TITLE
Tie Captured

### ISSUE THREAD

**Issue by Immelman51** [geordanr/xwing#499]
Hello, I don't find the Tie Captured modification for Sabine' Tie Fighter. Thank you for modifying that.

**Comment by geordanr** [comment]
What language translation are you using?

**Comment by Immelman51** [comment]
French

Envoyé de mon iPad

Le 17 sept. 2017 à 23:04, Geordan Rosario <notifications@github.com<mailto:notifications@github.com>> a écrit :


What language translation are you using?
