### ISSUE TITLE
Request: print cards

### ISSUE THREAD

**Issue by mruseless1** [geordanr/xwing#500]
Great squad builder, love it. 
I'm sure you've gotten this request a bunch, but could you add the ability to print squads as the images of the actual cards? Squadron Builder does this and it's the ONLY feature that they have that I use :)

**Comment by geordanr** [comment]
I don't include the images of actual cards so as to avoid any potential lawsuits from The Mouse.

**Comment by mruseless1** [comment]
Oh, that's interesting. How do the other sites avoid it?

---------------------------
There are only three kinds of people in this world.... those who can count,
and those who can't.
-- Author unknown

**Comment by mkrannich** [comment]
Export a list in XWS and visit http://meta-wing.com/squad_visualizations/ for your card view.

**Comment by mruseless1** [comment]
Excellent, thanks for the workaround.

---------------------------
There are only three kinds of people in this world.... those who can count,
and those who can't.
-- Author unknown
