### ISSUE TITLE
Punishing one upgrades

### ISSUE THREAD

**Issue by Meoni** [geordanr/xwing#519]
Upgrades are shown as:
Upgrades | Elite, Crew, Illicit
-- | --
Card shows Mech slot and 2x Torps.

**Comment by geordanr** [comment]
The JumpMaster 5000 upgrade icons were changed in the errata in [FAQ v4.4.0](https://images-cdn.fantasyflightgames.com/filer_public/d3/a1/d3a14aef-2f11-4eaa-a4c4-7419fdf6c30c/x-wing_faq_v440.pdf).
