### ISSUE TITLE
Scum doesn't let you add a 2nd pilot

### ISSUE THREAD

**Issue by LanikTnt** [geordanr/xwing#520]
Unlike the Imperial and Rebel factions, when you are building a scum list, it doesn't give you the option to add a 2nd pilot after you have setup a 1st pilot.  This used to work.  Clone pilot doesn't work either as a possible workaround.

**Comment by geordanr** [comment]
It's working for me; can you provide steps to reproduce the problem?

You may need to clear your browser's cache in order to load the latest version of the code.

**Comment by LanikTnt** [comment]
It's working for me now too.  Wierd.  Thanks
