### ISSUE TITLE
Yet anotherone Quadjumper

### ISSUE THREAD

**Issue by lyver** [geordanr/xwing#521]
on the Yetanotherone website, we see that que Quadjumper can do a move of straight one, but in reality , he does not have that move. thx,I hope that I'm wrong because I would like that

**Comment by zavrtak** [comment]
Good news. you are wrong. 
The Quad Jumper has a white one straight and a red reverse one straight. 

Quadjumper dial:
https://images-cdn.fantasyflightgames.com/filer_public/cf/68/cf681f4d-b719-4e1d-9e1d-2837ca1d88a2/swx61_dial.png
