### ISSUE TITLE
Alpha Class Star Wing Dial is wrong

### ISSUE THREAD

**Issue by merriry** [geordanr/xwing#526]
it shows the 4 straight as red, in the preview article it is shown as being white.

**Comment by geordanr** [comment]
The article shows this:
![Star Wing dial](https://images-cdn.fantasyflightgames.com/filer_public/40/0b/400bd56b-4bb9-4046-a5b3-2575f7a40088/swx69_maneuver_dial.png)

(Not to be confused with the Decimator dial, which is also linked in the article and does have a white 4 straight.)

**Comment by merriry** [comment]
I stand corrected. The Star Wing dial is also unhelpfully not in the image carousel. I opened that and scrolled through, saw one dial and assumed it was the correct dial. it's even oriented exactly the same.
