### ISSUE TITLE
Saved Squads NOT Appearing in Load Squad List

### ISSUE THREAD

**Issue by aogxcorps** [geordanr/xwing#557]
Not sure how to duplicate the issue.  I was squad building for a new game mode and saving them as "Bounty Hunt 1" for all 3 factions.  Four hours later, I went back to squad building.  To my dismay, when I clicked on "Load Squad", "Bounty Hunt 1" is missing from the list for Imperial and Scum.  Yet, it does show for Rebels.

I thought the Imperial and Scum squads I built were not saved.  So, I went about building new squads for those two factions.  When I went to save these squads with the same name of "Bounty Hunt 1", I received "You already have a squad with that name" error message.  Huh?

I clicked on "Load Squad" and there is no squad listed as "Bounty Hunt 1".  The same error happens on my desktop computer and smartphone.  I also deleted some saved squads -- thinking there is maximum squads your account can have.  But no fix.

Not sure what happened.  Any ideas on how to fix this?  Thanks in advance.

**Comment by zavrtak** [comment]
I think I am missing as well squads. So I can confirm that there is an issue.

**Comment by aogxcorps** [comment]
Okay.  I am stupid.  It finally dawned on me the other day why this is happening.

Your squad lists cannot share the same name across factions.  Case closed.  I suck for not realizing this sooner.

Tho, it would be nice if you can create lists across multiple factions using the same name.  Not too important.  But nice.  Carry on.
