### ISSUE TITLE
Russian roster editor translation

### ISSUE THREAD

**Issue by Foxygunische** [geordanr/xwing#565]
Hello Xwing roster editor team

I started playing the game a week ago. Here in Ukraine some people (including my girlfriend) are not good in English and would like to use roster editor for playing if it will have Russian-translated cards (to simplify involving in game).

As I can see, you have some person working on it, but there's still no Russian version of the editor available. If you are still planning to add Russian version, I'd like to help you translating from English into Russian.

The point is that only the 1st wave has official minis supported with Russian cards here, so my personal interest is that my girlfriend gets angry as we have last wave's cards in English only so she has to ask me for each card's translation few times per play.

If Russian version will be available, it will save a lot of nerves and will simplify for Russian speakers to get involved into play.

If you're interested (or not) - please reply

Thanks in advance,

Fox

**Comment by geordanr** [comment]
I would be happy to have help with adding Russian translations!

To add a new translation, a new translation file needs to be added.  The files are named `cards-XX.coffee` where `XX` is the country code for the language, so in this case we would have a new `cards-ru.coffee` file that contains the translations.

That file would then look something like this: https://github.com/geordanr/xwing/blob/master/coffeescripts/cards-es.coffee (the Spanish translation)

So if you can provide a file that contains these translations, I can incorporate it into the project.  How familiar are you with using GitHub for code collaboration?

**Comment by Foxygunische** [comment]
Not familiar at all. 

I took Spanish example and filling it now changing Spanish for Russian, will need some time to complete. Once will be done will upload here as text file, if won't succeed uploading to other files in coffeescripts folder

**Comment by Foxygunische** [comment]
Translation done. Now checking with few guys from local community, once will finish - will try to upload in coffeescripts folder (or email you, if you'll provide email address to send translation to)

Btw, I fixed some issues encountered in Spanish file. For example, in Proton Bombs section there's no description what bomb actually does (this part's missing in Spanish document, so I added it to Russian translation by myself)

**Comment by geordanr** [comment]
You should be able to attach files here.  If not you can upload them to https://gist.github.com/ and share the link.

**Comment by Foxygunische** [comment]
Corrections has been made. Attaching file here, hope will be incorporated soon)
[XWing russian translation.docx](https://github.com/geordanr/xwing/files/1870417/XWing.russian.translation.docx)

**Comment by geordanr** [comment]
Merged in.  Thanks!

**Comment by Foxygunische** [comment]
Also on Leebo (crew) it should be "Ускорение" instead of "Бочку" (just messed up Boost and Barrel Roll)

**Comment by geordanr** [comment]
In the future please submit new bug reports for updates to the translation file as this bug is now closed.
