### ISSUE TITLE
Update Rebel Content, from FFG Article

### ISSUE THREAD

**Issue by emeraldbeacon** [geordanr/xwing#575]
## New Content Available

3 new rebel pilots, 1 Imperial Pilot, and 4 new upgrades are available to input into the system, from this article:  https://www.fantasyflightgames.com/en/news/2018/4/24/save-the-rebellion/

I'd update it if I knew how!

### Language

English

**Comment by geordanr** [comment]
Sorry about the delay; the article was released when I was on a flying out on vacation.

**Comment by emeraldbeacon** [comment]
No worries!  Apropos of nothing, the TIE Reaper article went live today, too.  Complete with maneuver dial!
