### ISSUE TITLE
Math is wrong

### ISSUE THREAD

**Issue by diablodiablo** [geordanr/xwing#581]
## YASB Bug Report

**Note:** If you are experiencing problems with the permalink URL when you have **Maul** or **Bomblet Generator** in your list, this is a known issue.  For more information please see https://www.reddit.com/r/XWingTMG/comments/7c4q6h/yet_another_squad_builder_problems_with_maul/

### Expected Behavior

State what you expect to happen here.
28+3+4-2 =33

### Actual Behavior

State what actually happens here.
Added up to 32
https://geordanr.github.io/xwing/?f=Rebel%20Alliance&d=v4!s!5:57,264,3:-1:20:M.34&sn=Unnamed%20Squadron&obs=

### Language

State what language translation you use.
English

**Comment by sirjorj** [comment]
You forgot the -1 EPT cost from Renegade Refit.

**Comment by geordanr** [comment]
Closing as behavior appears to be correct.
