### ISSUE TITLE
Sign in with Twitter not working, tried on several machines and networks

### ISSUE THREAD

**Issue by astrandxwing** [geordanr/xwing#582]
## YASB Bug Report

**Note:** If you are experiencing problems with the permalink URL when you have **Maul** or **Bomblet Generator** in your list, this is a known issue.  For more information please see https://www.reddit.com/r/XWingTMG/comments/7c4q6h/yet_another_squad_builder_problems_with_maul/

### Expected Behavior

State what you expect to happen here.

### Actual Behavior

State what actually happens here.

### Language

State what language translation you use.

**Comment by sirjorj** [comment]
I just noticed this too.  I think twitter recently shut down some older API calls.  That could be the cause of this issue.

**Comment by geordanr** [comment]
Fixed; had to configure an extra callback URL because of https://twittercommunity.com/t/action-required-sign-in-with-twitter-users-must-whitelist-callback-urls/105342

**Comment by astrandxwing** [comment]
Thanks!
