### ISSUE TITLE
Crew with Actions not Added to Action Bar

### ISSUE THREAD

**Issue by Ellauff** [geordanr/xwing#597]
## YASB Bug Report

**Note:** If you are experiencing problems with the permalink URL when you have **Maul** or **Bomblet Generator** in your list, this is a known issue.  For more information please see https://www.reddit.com/r/XWingTMG/comments/7c4q6h/yet_another_squad_builder_problems_with_maul/

### Expected Behavior

When Director Krennic is added to a ship as crew, that ship should gain the Target Lock Action on its Action Bar. Thus upgrades, such as Grand Moff Tarkin which require the ship to have the Target Lock Abilitiy to be equipped should now be equipable.

### Actual Behavior

Squad builder does not recognize that abilities gained from Crew are added to the Action Bar.

### Language

English

**Comment by geordanr** [comment]
This repo is only for the 1.0 version of the builder.  You'll want to file this issue at https://github.com/raithos/xwing (once issues are enabled there).
