### ISSUE TITLE
CROC Missing Havy Laser Turet

### ISSUE THREAD

**Issue by BobaFett98** [geordanr/xwing#602]
### This bug report filer is for First Edition X-Wing only!

**Note:** If you are experiencing problems with the permalink URL when you have **Maul** or **Bomblet Generator** in your list, this is a known issue.  For more information please see https://www.reddit.com/r/XWingTMG/comments/7c4q6h/yet_another_squad_builder_problems_with_maul/

### Expected Behavior

State what you expect to happen here.

### Actual Behavior

State what actually happens here.

### Language

State what language translation you use.

**Comment by BobaFett98** [comment]
I miss the Havy Laser Turet

**Comment by elistevens** [comment]
Mmm, perfect.
