### ISSUE TITLE
Log In Button Not Working at All

### ISSUE THREAD

**Issue by Spectrumhazard** [geordanr/xwing#606]
### This bug report filer is for First Edition X-Wing only!

**Note:** If you are experiencing problems with the permalink URL when you have **Maul** or **Bomblet Generator** in your list, this is a known issue.  For more information please see https://www.reddit.com/r/XWingTMG/comments/7c4q6h/yet_another_squad_builder_problems_with_maul/

### Expected Behavior

Press “Log In” to log in and view saved squadrons

### Actual Behavior

Log in gui highlights but does not activate anything or redirect, just stays highlighted

### Language

State what language translation you use.

**Comment by geordanr** [comment]
Fixed in https://github.com/geordanr/xwing-backend/commit/9453cf37b0d608bd250ad2f08959abeed2117472 and added `geordanr.github.io` as an allowed origin.
